[package]
name = "minimization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
log2 = "0.1.10"
nalgebra = "0.32.3"
plotters = "0.3.5"
utils = { path = "../utils" }
